export function isZipped(filePath: string, callback: Function): void;
export function unzip(filePath: string, callback: Function): void;
export function zip(files: any[], callback: Function): void;
export function openTemplate(templateId: string, callback: Function): void;
export function detectType(template: any): any;
export function _isXMLFile(template: any): boolean;
export function _isXHTMLFile(template: any): boolean;
export function _isHTMLFile(template: any): boolean;
export function _checkMimetypeFile(template: any, string: string): boolean;
export function _checkWordInFilename(template: any, string: string): boolean;
export function buildFile(report: any, callback: Function): any;
