declare var tmpDir: any;
export { tmpDir as tempPath };
export declare const templatePath: any;
export declare const factories: number;
export declare const attempts: number;
export declare const startFactory: boolean;
export declare const uidPrefix: string;
export declare const pipeNamePrefix: string;
export declare const extensionParsed: string;
export declare const lang: string;
export declare const translations: {};
export declare const currencySource: string;
export declare const currencyTarget: string;
export declare namespace currencyRates {
    const EUR: number;
    const USD: number;
    const JPY: number;
    const BGN: number;
    const CZK: number;
    const DKK: number;
    const GBP: number;
    const HUF: number;
    const PLN: number;
    const RON: number;
    const SEK: number;
    const CHF: number;
    const ISK: number;
    const NOK: number;
    const HRK: number;
    const RUB: number;
    const TRY: number;
    const AUD: number;
    const BRL: number;
    const CAD: number;
    const CNY: number;
    const HKD: number;
    const IDR: number;
    const ILS: number;
    const INR: number;
    const KRW: number;
    const MXN: number;
    const MYR: number;
    const NZD: number;
    const PHP: number;
    const SGD: number;
    const THB: number;
    const ZAR: number;
}
//# sourceMappingURL=params.d.ts.map