export function isCarboneMarker(oneMarker: string): boolean;
export function findMarkers(xml: string, callback: Function): void;
export function removeXMLInsideMarkers(xml: string): string;
export function extractMarker(markerStr: string): string;
export function cleanMarker(markerStr: string): string;
export function replaceEncodedOperatorCharactersByNoEncodedCharacters(str: string): string;
export function replaceNoEncodedOperatorCharactersByEncodedCharacters(str: string): string;
export function cleanXml(xml: string): string;
export function removeWhitespace(str: string): string;
export function translate(xml: string, options: any, callback: Function): any;
export function findVariables(xml: string, existingVariables: any[], callback: Function): any;
export function preprocessMarkers(markers: any[], variables: any[], callback: any): void;
export function assignLoopId(markers: any[]): any[];
export function findOpeningTagPosition(leftSideXml: string, indexWhereToStopSearch: integer): integer;
export function findClosingTagPosition(rightSideXml: string, indexWhereToStartSearch: integer): integer;
export function findPivot(partialXml: string): object;
export function findRepetitionPosition(xml: string, pivot: object, roughStartIndex: integer): object;
export function flattenXML(xml: string): any[];
export function moveConditionalBlockBeginEnd(xmlTree: any[], beginFlattenXMLIndex: Integer, beginTextIndex: Integer, endTextIndex: Integer): any;
export function findSafeConditionalBlockPosition(xmlFlattened: string, beginTextIndex: any, endTextIndex: any): any[];
export function parseMathematicalExpression(mathExpr: string, safeVariableInjectionFn: Function): string;
//# sourceMappingURL=parser.d.ts.map